on:
  push:
    paths:
      - 'infra/**'
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build Lambda Package
        run: |
          mkdir -p infra/lambda
          zip -j infra/lambda/updateVisitorCount.zip backend/lambda_function.py
          ls -lh infra/lambda/updateVisitorCount.zip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Deploy
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
