on:
  push:
    paths:
      - 'infra/**'
      - 'backend/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build Lambda Package
        run: |
          mkdir -p infra/lambda
          zip -j infra/lambda/updateVisitorCount.zip backend/lambda_function.py
          ls -lh infra/lambda/updateVisitorCount.zip

      - name: Configure AWS Credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::681121191318:role/GithubAdminAccess
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Deploy
        env:   
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ steps.aws_creds.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws_creds.outputs.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ steps.aws_creds.outputs.AWS_SESSION_TOKEN }}
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve
